export const Add_INGREDIENT = 'Add_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const INITIAL_INGREDIENT = 'INITIAL_INGREDIENT';

export const BURGER_ORDERSTART = 'BURGER_ORDERSTART';
export const ORDER_INGREDIENTSUCCESS = 'ORDER_INGREDIENTSUCCESS';
export const ORDER_INGREDIENTFAILED = 'ORDER_INGREDIENTFAILED';
export const BURGER_ORDER_SAGA = 'BURGER_ORDER_SAGA';
export const FATECH_ORDER_SAGA = 'FATECH_ORDER_SAGA';

export const FETCHDATA_START = 'FETCHDATA_START';
export const FETCHDATA_SECCUSS = 'FETCHDATA_SECCUSS';
export const FETCHDATA_FAILED = 'FETCHDATA_FAILED';

export const SUBMIT_AUTH_SCUCCESS = 'SUBMIT_AUTH_SCUCCESS';
export const SUBMIT__AUTH_START = 'SUBMIT__AUTH_START';
export const SUBMIT_AUTH_FAILED = 'SUBMIT_AUTH_FAILED';
export const AUTH_INITITATE_LOGOUT = 'AUTH_INITITATE_LOGOUT';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_AUTO_CHECK = 'AUTH_AUTO_CHECK';

export const USERLOGEOUT_SCUCCESS = 'USERLOGEOUT_SCUCCESS';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';